[algorithm]
processing_scale = 0.5
path_root_y_threshold = 5
sidebar_height = 100
blackbar_height = 300

[algorithm.thresholds.colors]
blue = [105, 173, 130]
yellow = [35, 75, 165]
magenta = [150, 0, 100]
red = [150, 0, 0]

[algorithm.thresholds.ranges]
blue = [15, 255, 255]
yellow = [22, 104, 79]
magenta = [150, 0, 100]
red = [150, 0, 0]

[algorithm.denoising]
image_edge_distance = 5

[hardware]
enable = true
port = "/dev/ttyUSB0"
baudrate = 115200
update_freq = 25
legacy_chassis = true
camera_id = 0

[hardware.limits]
max_speed = 1.0
max_turn = 1.0
max_strafe = 1.0

[hardware.pid.steering]
Kp = 3.0
Kd = 0.5
Ki = 0

[hardware.pid.strafing]
Kp = 3.0
Kd = 0.5
Ki = 0

[hardware.control.speeds]
min = 0.6
max = 0.6

[hardware.control.steering]
max = 0.6
min = 0.3

[hardware.control.strafing]

[display]
use_remote = true
remote_address = "192.168.81.74:0"
