[algorithm]
processing_scale = 0.5
path_root_y_threshold = 5
sidebar_height = 40
blackbar_height = 0
color_loss_threshold = 0.002
display = false
use_photos = false

[algorithm.thresholds.colors]
blue = [103, 108, 199]
yellow = [27, 60, 193]
magenta = [163, 120, 73]
red = [150, 0, 0]

[algorithm.thresholds.ranges]
# blue = [9, 132, 112]
# yellow = [6, 55, 123]
blue = [15, 500, 500]
yellow = [15, 500, 500]
magenta = [13, 90, 500]
red = [150, 0, 0]

[algorithm.thresholds.min]
yellow = [0, 40, 180]
blue = [0, 40, 50]

[algorithm.thresholds.max]
yellow = [255, 255, 255]
blue = [255, 255, 255]

[algorithm.pathfinding.thresholds]
laplacian = 148

[algorithm.denoising]
image_edge_distance = 2

[algorithm.navigation]
default_target_x = 0.5
default_target_y = 0.1
history_weighting = 0.4
color_loss_offset = 0.5
avg_size = 1


[hardware]
enable = true
port = "/dev/ttyACM0"
baudrate = 115200
update_freq = 25
legacy_chassis = true
camera_id = 0

[hardware.limits]
max_speed = 1000
max_turn = 1000
max_strafe = 1000
max_sum = 1000

[hardware.pid.steering]
Kp = 3.0
Kd = 1
Ki = 0

[hardware.pid.strafing]
Kp = 3.0
Kd = 0
Ki = 0

[hardware.control.speeds]
max = 600
min = 50

[hardware.control.steering]
max = 600
min = 50

[hardware.control.strafing]
max = 4100
min = 50

[display]
use_remote = true
remote_address = "192.168.81.74:0"
