[algorithm]
processing_scale = 0.5
path_root_y_threshold = 5
sidebar_height = 1
blackbar_height = 0
color_loss_threshold = 0.0015
display = false
use_photos = false

[algorithm.thresholds.colors]
blue = [103, 108, 199]
yellow = [27, 60, 193]
magenta = [163, 150, 73]
red = [4, 117, 188]
green = [74, 67, 199]

[algorithm.thresholds.ranges]
# blue = [9, 132, 112]
# yellow = [6, 55, 123]
blue = [15, 500, 500]
yellow = [15, 500, 500]
magenta = [13, 120, 500]
red = [9, 163, 133]
green = [8, 51, 51]

[algorithm.thresholds.min]
yellow = [0, 40, 180]
blue = [0, 60, 50]

[algorithm.thresholds.max]
yellow = [255, 255, 255]
blue = [255, 255, 255]

[algorithm.pathfinding.thresholds]
laplacian = 148
second_pass_threshold = 0.4

[algorithm.denoising]
image_edge_distance = 2

[algorithm.navigation]
default_target_x = 0.45
default_target_y = 0.5
history_weighting = 0.3
color_loss_offset = 0
avg_size = 2
ratio_biasing = 200


[hardware]
enable = true
port = "/dev/ttyACM0"
baudrate = 115200
update_freq = 25
legacy_chassis = true
camera_id = 0

[hardware.limits]
max_speed = 1000
max_turn = 1000
max_strafe = 1000
max_sum = 1000

[hardware.pid.steering]
Kp = 3.0
Kd = 2
Ki = 0

[hardware.pid.strafing]
Kp = 3.0
Kd = 0
Ki = 0

[hardware.control.speeds]
max = 650
min = 50

[hardware.control.steering]
max = 500
min = 50


[hardware.control.strafing]
max = 5700
min = 50

[display]
use_remote = true
remote_address = "192.168.81.74:0"
